
// import Link from 'next/link'
// import type { ReactNode } from 'react'

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

// export default function RootLayout({ children }: {children: ReactNode}) {
//   return (
//     <html lang="en">
//         <body>
//             <nav>
//                 <ul>
//                     {
//                         ['Categories', 'Sale', 'Clearance', 'New Stock', 'Trending'].map((e)=>{
//                             return (<Link key={e} href={"#"}>{e}</Link>)
//                         })
//                     }
//                 </ul>
//             </nav>
//             {children}
//         </body>
//     </html>
//   )
// }